### ISSUE TITLE
Login to the application from a github account

### ISSUE THREAD

**Issue by yllieth** [yllieth/localehub#2]

**Comment by dehau** [comment]
Just tested github Oauth Web flow with your app client_id. It works well but I am wondering if we must go for a pure JS management of access_tokens (localstorage + route to handle redirect with code) or also keep it is some sort of backend (we probably need a backend for projects anyway and keeping tokens can be useful for https://github.com/yllieth/localehub/issues/8)

**Comment by dehau** [comment]
Storing github token inside localstorage seems dangerous since scopes like `repo` are not very granular and authorize much more then what we need after project creation. (when project is created, application must be limited to access and write to i18n locales files)

**Comment by yllieth** [comment]
I totally agree @dehau, we will need a backend. Do you have some time for a call this weekend ? It would be nice if we can achieve to setup the backend and an online platform asap (backend in priority).

✅ agree when you say that keeping github token in localstorage is dangerous. We definitively must avoid that.
✅ agree when you say that the application must be limited to write into i18n files (specified during project's setup). It's a key point that we must guarantee to our users (#5). Reading other files should be interesting to develop the v1.1 feature that search for usage of i18n strings in the code. But as it is not a MVP feature, we don't have to care about that for now.

**Comment by dehau** [comment]
@yllieth of course. If you are still in PDT timezone, maybe we can Schedule it this evening (CEST)

**Comment by yllieth** [comment]
@dehau I'm back in Trébeurden ! Slack me when you are available ...

**Comment by yllieth** [comment]
- [x] create AWS lambdas handling oauth requests to sign in through github oauth API
- [x] store github access token in an AWS database and only expose internal tokens
- [x] sign-in through github oauth login page and retreive this internal token (d6b618e8aba36c5d0f76d94fc9f3f9d7ce11e3c5)
  - link login button in the interface to prompt github oauth login page
  - retreive the github code returned in the url
  - retreive the internal token (the image of the github access token)
- [x] setup all API requests to send this token in the `Authorization` header
- [x] forbid access to application pages if this token is absent (redirect to `/login`) (1c7f044a4fc3a24ac935d406535775f334a46be2)
